### ISSUE TITLE
ValueError: 'te' is not in list (on clean installation)

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#169]
First ran properties script,
next ran demand script.

error:
```
ValueError: 'te' is not in list
```

**Comment by daren-thomas** [comment]
this turned out to be a problem with git-lfs: @martin-mosteiro had not installed git-lfs. He didn't install it, because we did not tell him to do so in the dev manual installation guide. @martin-mosteiro is going to update the guide to fix this.

after installation of git-lfs, re-clone the reference-case, voilà! problem solved!

(this issue will stay open until the dev manual installation guide has been updated.

**Comment by daren-thomas** [comment]
@martin-mosteiro: have you updated the documentation yet?

**Comment by martin-mosteiro** [comment]
I did! Just added point 9 to the installation guide.
