### ISSUE TITLE
Problem when calculating the cooling demand

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#202]
During the test run workshop, we changed the energy supply and emissions systems for all the buildings in the area. When this happens, the cooling demand is not generated and the heat maps come out with one tint (0 values).

However, when we change the systems for some of the buildings within the area of study only, the cooling demand and heat maps are generated accordingly.

Can we take a look at this issue?

**Comment by amraladdin** [comment]
@JIMENOFONSECA Did you have time to check this error? Who can take care of this error?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle could you take a look when the new iHVAC model be ready?

**Comment by amraladdin** [comment]
Thanks!

**Comment by gabriel-happle** [comment]
@amraladdin what do you mean exactly? Buildings only have a cooling demand if they actually have a cooling system. Do you want to calculate the theoretical demand to reach comfortable zone air temperature with a hypothetical system?

**Comment by martin-mosteiro** [comment]
I can explain, since Amr is out at the moment.

During the workshop, we created a few energetic scenarios: the current situation and various other systems for heating, cooling and hot water. The cooling demand was not zero for the current situation and for the scenarios I ran. However, the cooling demand was zero for all buildings for all the scenarios created by the workshop participants (no error messages or anything like that came up during their simulations).

Since the demand for the baseline case was not zero, there should be a cooling demand for all cases regardless of the supply system defined. I thought maybe the problem could be that they used the wrong string format when inputting the energy system type, but their heating and hot water calculations were correct. It could also be an error in the type of systems they used, but my scenario had the same energy system as two of the scenarios the participants defined, yet mine ran fine and theirs didn’t.

The only difference between the scenarios I ran and the ones the participants created was that they changed the energy systems for all buildings in the reference case, whereas I only changed the buildings within the zone of study - this shouldn’t cause any problem, of course, but maybe it did somehow?




On 26 May 2016, at 13:59, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@amraladdin<https://github.com/amraladdin> what do you mean exactly? Buildings only have a cooling demand if they actually have a cooling system. Do you want to calculate the theoretical demand to reach comfortable zone air temperature with a hypothetical system?

**Comment by gabriel-happle** [comment]
@martin-mosteiro what do you mean with supply system? I was talking about the emission system 'type_cs' in the HVAC worksheet of the archetypes DB. Only Buildings with HVAC cooling have a cooling demand in the present CEA. Does that answer your question?

Of course the string format could also be an issue...

**Comment by JIMENOFONSECA** [comment]
fixed
