### ISSUE TITLE
Move 4-Technical to DB and change folder structure

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#218]
4-technical is a database which barely depends on the scenario. It should then be moved to cea/db together with the Archetypes and the weather data DBs.

This brings about the opportunity to make the folder structure much more easy to read. here is an example @architecture-building-systems/cea please comment until 27.06.17 

![capturenew](https://cloud.githubusercontent.com/assets/8973186/15563345/704994bc-233a-11e6-961b-e71de6e2902a.PNG)
possible.

**Comment by JIMENOFONSECA** [comment]
This is the existing one btw:

![capture22222](https://cloud.githubusercontent.com/assets/8973186/15563358/8ba1254a-233a-11e6-9327-91732fd7cb06.PNG)

**Comment by daren-thomas** [comment]
due to the use of the input locator, making these changes should be
easy-peasy :)

**Comment by martin-mosteiro** [comment]
Agreed that it makes no sense to have “technical” as an input here. Question: I was including the SIA Standard-based mobility calculations in the technical folder (in order to generate “embodied”, “operation” and “mobility” results). Should these go in the “db” folder as well then? Won’t this make the tool very Swiss-based?

The general folder structure looks a lot clearer to me now than before, agreed on that too :)




On 26 May 2016, at 06:07, JIMENOFONSECA <notifications@github.com<mailto:notifications@github.com>> wrote:


4-technical is a database which barely depends on the scenario. It should then be moved to cea/db together with the Archetypes and the weather data DBs.

This brings about the opportunity to make the folder structure much more easy to read. here is an example @architecture-building-systems/cea<https://github.com/orgs/architecture-building-systems/teams/cea> please comment until 27.06.17

[capturenew]<https://cloud.githubusercontent.com/assets/8973186/15563345/704994bc-233a-11e6-961b-e71de6e2902a.PNG>
possible.

**Comment by JIMENOFONSECA** [comment]
About the 2000-watt society we can may be put it in a folder called ..db/benchmarks?.
we could also create all these databases for different regions. Perhaps we put later on everything in a folder called db/switzerland/benchmarks
db/switzerland/archetypes
db/switzerland/weather
etc....

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @gabriel-happle @amraladdin @shizhongming please comment in the folder structure. today i expect to start implementing the changes

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA The new folder structure does make more sense now! 
one question, under the folder "building geometry", are both district.shp and zone.shp providing building geometry information? or is the district.shp containing building geometry information, and zone.shp is indicating the group of building in the district that will be simulated?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh i see them both storing building geometry. one of the entire district and one of the zone to be analyzed. but probably we would like to include a way to do zoning in the other areas of the district

**Comment by gabriel-happle** [comment]
This structure makes sense to me.

**Comment by martin-mosteiro** [comment]
db/switzerland/etc. sounds good to me


On 26 May 2016, at 11:05, JIMENOFONSECA <notifications@github.com<mailto:notifications@github.com>> wrote:


About the 2000-watt society we can may be put it in a folder called ..db/benchmarks?.
we could also create all these databases for different regions. Perhaps we put later on everything in a folder called db/switzerland/benchmarks
db/switzerland/archetypes
db/switzerland/weather
etc....

**Comment by daren-thomas** [comment]
can we use the country codes instead?

- `db/switzerland` vs. `db/ch/`

**Comment by JIMENOFONSECA** [comment]
sure thing

**Comment by amraladdin** [comment]
I think the new structure is much nicer, and I agree with Daren to use country codes
