### ISSUE TITLE
tds creating high overhead

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#262]
Working with data frames creates a high overhead in the demand calculation. 

I observed this in the first implementation back in August 2014. I created the tool following only data frames.  By changing everything to numpy arrays and lists (As in the CEA tool last deployed version) the performance increased dramatically. From 1 min to 2 sec calculation per building!

Somehow we got into this structure of managing and sending the dataframe "tds" everywhere again. We might want to go one step back and change again to single numpy arrays. 

numpy arrays can as well work with multiprocessing. could we reverse this change @daren-thomas ?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, check out pull request #263: speedup after moving to `dict` instead of `Dataframe`

**Comment by JIMENOFONSECA** [comment]
We moved to dicts. It seems a temporal solution. @gabriel-happle @daren-thomas any suggestion?

**Comment by daren-thomas** [comment]
Can we say temporary instead of temporal? Temporal refers to temperatures...

I actually like using the dict as a namespace for state data of the
simulation. It is fast. It keeps all the variables nicely in a single
namespace and will make documenting all the state variables of the
calculations sooo much easier, as they are then always named the same in
every function and are all in one place.

Also, this allows us to use names for these variables that are closer to
the physical names without breaking pythons naming conventions. In fact, we
could even use latex syntax to make it easier to write subscripts and
superscripts and stuff like that...

You seem unhappy. Can you please explain?

**Comment by JIMENOFONSECA** [comment]
I believe compromising performance does not necessarily takes us one step forward. We will need to evaluate this before implementing more carefully and probably subject this to a meeting with the board.

Looking at the future complexity of the tool and the restrictions that this might cause to the user and testers, every second of computation we save will matter.

**Comment by JIMENOFONSECA** [comment]
fixed with #279
