### ISSUE TITLE
Swiss database contains calculation errors

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#345]
The current supply_system database includes the following values (the units are not shown in the database, so they are my assumption):

**T1 - swiss consumer energy mix:** 2.63 kWh PEN/kWh and 0.0413 kg CO2/kWh
**T2 - PVT panel - monocrystalline roof top:** 0.278 kWh PEN/kWh and 0.0202 kg CO2/kWh
**T3 - PVT- monocrystalline roof top:** 0.222 kWh PEN/kWh and 0.0108 kg CO2/kWh
**T4 - swiss consumer energy mix 70% + 30% PV:** 0.1535 kWh PEN/kWh and 0.0002 kg CO2/kWh
**T5 - swiss consumer energy mix  70% + 30% PVT:** 0.1226 kWh PEN/kWh and 0.0001 kg CO2/kWh

I see a couple of problems with these. First of all: T2 and T3 are basically defined as the same thing. T2 should be PV and T3 PVT?

Secondly and more importantly: How can a combination of the consumer energy mix and solar panels have a **lower** primary energy and CO2 emissions per kWh than either the consumer energy mix or the solar panels alone? Well, T4 and T5 are calculated as follows:
PEN_T5 = 0.7 * PEN_T1 * 0.3 * PEN_T3 and CO2_T5 = 0.7 * CO2_T1 * 0.3 * CO2_T3
i.e., instead of adding the two, they are multiplied, so the results are lower than they should be.

I am now fixing both of these errors. However, @JIMENOFONSECA: could you provide the source for these energy mixes used? It would be good in any case to include the source in the manual or somewhere else. This way we can try to be consistent with this source when defining other systems and energy mixes (e.g., Belgium).

**Comment by martin-mosteiro** [comment]
I just corrected the mistakes in the Excel file. The only thing missing is the source of the factors used.

**Comment by JIMENOFONSECA** [comment]
Hi, the source are the ökobilanzdaten analysis of the kbob for buildings

https://www.kbob.admin.ch/dam/kbob/de/dokumente/Publikationen/Nachhaltiges%20Bauen/Empfehlung_Oekobilanzdaten_Baubereich_2009_1_2014.pdf.download.pdf/Empfehlung%20Ökobilanzdaten%20im%20Baubereich%202009/1_2014.pdf


Best, Jimeno

On 23 Sep 2016, at 22:06, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


The current supply_system database includes the following values (the units are not shown in the database, so they are my assumption):

T1 - swiss consumer energy mix: 2.63 kWh PEN/kWh and 0.0413 kg CO2/kWh
T2 - PVT panel - monocrystalline roof top: 0.278 kWh PEN/kWh and 0.0202 kg CO2/kWh
T3 - PVT- monocrystalline roof top: 0.222 kWh PEN/kWh and 0.0108 kg CO2/kWh
T4 - swiss consumer energy mix 70% + 30% PV: 0.1535 kWh PEN/kWh and 0.0002 kg CO2/kWh
T5 - swiss consumer energy mix 70% + 30% PVT: 0.1226 kWh PEN/kWh and 0.0001 kg CO2/kWh

I see a couple of problems with these. First of all: T2 and T3 are basically defined as the same thing. T2 should be PV and T3 PVT?

Secondly and more importantly: How can a combination of the consumer energy mix and solar panels have a lower primary energy and CO2 emissions per kWh than either the consumer energy mix or the solar panels alone? Well, T4 and T5 are calculated as follows:
PEN_T5 = 0.7 * PEN_T1 * 0.3 * PEN_T3 and CO2_T5 = 0.7 * CO2_T1 * 0.3 * CO2_T3
i.e., instead of adding the two, they are multiplied, so the results are lower than they should be.

I am now fixing both of these errors. However, @JIMENOFONSECA<https://github.com/JIMENOFONSECA>: could you provide the source for these energy mixes used? It would be good in any case to include the source in the manual or somewhere else. This way we can try to be consistent with this source when defining other systems and energy mixes (e.g., Belgium).

**Comment by JIMENOFONSECA** [comment]
btw, I am afraid something is happening with the databases. This error was corrected about twice already last year... did you modified the master?

**Comment by martin-mosteiro** [comment]
I had modified the master, yes. My apologies for not creating a branch, I should have done that.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro no problem, next time..
