### ISSUE TITLE
calc_Eaf should probably be calculated based on Aef instead of Af

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#360]
Currently, `calc_Eaf` (final electrical consumption due to appliances) uses the input variable `Af` (conditioned floor area (heated/cooled) in [m2]). I think we should use the input variable `Aef` (floor area with electricity in [m2]) instead.

@JIMENOFONSECA: Is this a bug? Do we need to change it?

**Comment by daren-thomas** [comment]
The answer to this bug needs to be added to the documentation in the `calc_Eaf` function on the documentation-and-refactoring branch.

**Comment by daren-thomas** [comment]
Also, this function could easily be inlined (it is just a multiplication: `Eaf = schedule * Ea_Wm2 * Aef`)

**Comment by JIMENOFONSECA** [comment]
Yes, all should be changed to that.

Best, Jimeno

On 12 Oct 2016, at 17:01, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, this function could easily be inlined (it is just a multiplication: Eaf = schedule * Ea_Wm2 * Aef)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, I'm not quite sure what you mean. What exactly should be changed?

1. change to Aef instead of Af
2. inline (remove function invocation)
3. find other such functions with this problem (candidates: `calc_Elf`)

**Comment by JIMENOFONSECA** [comment]
all :-)

On 13 Oct 2016, at 3:50 pm, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA>, I'm not quite sure what you mean. What exactly should be changed?

  1.  change to Aef instead of Af
  2.  inline (remove function invocation)
  3.  find other such functions with this problem (candidates: calc_Elf)

**Comment by daren-thomas** [comment]
fixed with PR #367
