### ISSUE TITLE
Hochschulquartier reference case incomplete

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#368]
The shapefiles for the Hochschulquartier aren't entirely accurate:
1. the LEO building from the ETH has been in operation since 2014, but it is not included in the shapefile
2. the zone of study does not include the Kunsthaus - which is actually part of the perimeter of the Masterplan
3. other buildings have already been demolished - however, I would argue that the Baseline reference case provides a valid "before" reference, whereas the Masterplan reference case would provide the "after" reference, so it's fine for these buildings to be there.

The LEO building is not part of the Masterplan, though, and should be included in the Baseline reference case. Based on discussion with @JIMENOFONSECA, we should fix this issue ourselves (rather than ordering new shapefiles from the City of Zurich).

**Comment by martin-mosteiro** [comment]
This issue is solved, but the new reference case needs to be uploaded to our reference case repository. I will do so today.

Note: this will require adding additional supply systems to our database, see #555.

**Comment by JIMENOFONSECA** [comment]
Cool, be aware of the new type of files we have. Thermal_loads got suppressed and the architecture.shp and zone.shp changed. However if you upload de case study, i can help you out with this shift.

Best, Jimeno

On 23 Mar 2017, at 17:17, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


This issue is solved, but the new reference case needs to be uploaded to our reference case repository. I will do so today.

Note: this will require adding additional supply systems to our database, see #555<https://github.com/architecture-building-systems/CEAforArcGIS/issues/555>.

**Comment by martin-mosteiro** [comment]
Update: even after the latest update of the Masterplan reference case, there are still two new buildings missing, the Hirschengrabenbau and Plattenstrasse 22/24. Information on the former is rather scarce, but these buildings will be drawn into the reference case later.

**Comment by martin-mosteiro** [comment]
Plattenstrasse 22/24 was added based on [the building plans](oerebdocs.zh.ch/getDoc?docid=4023). The Hirschengrabenbau was also added, though since no plans could be found it was based on [the ground floor area](http://www.are.zh.ch/dam/baudirektion/are/raumplanung/kantonalerrichtplan/vorlagen/oeba_4349/antrag_regierungsrat/Phase_2_masterplan_minimal.pdf.spooler.download.1400169900471.pdf/Phase_2_masterplan_minimal.pdf), the height was assumed to be the same as the current maximum height and the number of floors was assumed based on the current useable floor area and the future useable floor area (HNF).

**Comment by martin-mosteiro** [comment]
This issue is mostly solved, the only open issue is the supply systems, which are now addressed in issue #720. This issue can therefore now be closed.
