### ISSUE TITLE
Discrepancy in the Data Helper generated values

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#372]
After the Exercise we gave to the MIBS students (which is to assume time of retrofitting for building components, in order to incorporate these values in the AGE shape file and have -hopefully- more accurate inputs). The following occured:
- In the cases when no renovation occurs, some students used "0" as an input value, while others used the "built" year (so if the building was built in 1870, they used 1870 for the non-retrofitted components).
- To be more specific, 2 students divided the hospital buildings between them, when they input their results, one of them used "0" for the age of non-retrofitted components, while the other used the "built" year.
- When they activated the Data helper, the U-values of the building components were different, although they should be the same. The buildings had the exact same occupancy and built year.

@JIMENOFONSECA would you have an explanation for this? Maybe it's in the calculation of how the Archetypes are made?
Who should I assign this task to?

**Comment by JIMENOFONSECA** [comment]
An interesting bug. Ask them to always use 0 if they have not been renovated. Use only the real built year in the 'built' column. 

Assign the issue to me. the bug will be solved until the end of the year. Is that ok?

**Comment by amraladdin** [comment]
Yeah, I already fixed all the non-retrofitted values to 0 and sent the new file to the students yesterday.
Yeah sure, end of the year is perfect, they'll continue working with these files from now on :)

Cool, thanks!

**Comment by daren-thomas** [comment]
Did the reference cases get updated with the new files sent to the students?

**Comment by JIMENOFONSECA** [comment]
@amraladdin any clue?

**Comment by amraladdin** [comment]
No, because changing the values to 0 for the age of retrofitting is a quick fix and not a long-term solution for the tool. Someone needs to check the calculations to see why this issue is happening. @JIMENOFONSECA , wasn't this issue assigned to you?

**Comment by JIMENOFONSECA** [comment]
yes it was. I thought it was solved already. Do you have any solution form the user perspective?. I am out of ideas in this topic

On 14 Nov 2016, at 4:46 pm, Amr Elesawy <notifications@github.com<mailto:notifications@github.com>> wrote:


No, because changing the values to 0 for the age of retrofitting is a quick fix and not a long-term solution for the tool. Someone needs to check the calculations to see why this issue is happening. @JIMENOFONSECA<https://github.com/JIMENOFONSECA> , wasn't this issue assigned to you?

**Comment by amraladdin** [comment]
No I don't, sorry. I guess we would need to see why this issue is happening in the code. Unfortunately, I don't have much time till the end of the year because of teaching.

@martin-mosteiro do you have an idea why this error is happening? Or any idea how to solve it?

**Comment by martin-mosteiro** [comment]
The explanation is pretty easy. Check this out:
![screen shot 2016-11-14 at 11 08 57](https://cloud.githubusercontent.com/assets/18548065/20260621/c6ab6a9a-aa5a-11e6-8114-f0c32c8d02a3.png)
A building **renovated** before 1920 has different U-values than one **built** before 1920. So that's what causes the problem. In order to avoid discrepancies, we could either:
1. tell people to use 0 for no renovation - this is what's been done so far, but apparently that is not user-friendly enough
2. add a check to the code that would first verify if the renovation year makes sense before calcualting the U-values. Something like
```
if (renovation_year - built_year) > 0:
calculate the U-values based on the renovation year
else:
calculate the U-values based on the built year
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas i see this as a kind of error handling error. In practice, the users should not be able to input the renovation year  equal to the construction year. could you help me to implement this? we might want to postpone this for the next milestone. I will put you in the loop

**Comment by martin-mosteiro** [comment]
Shouldn't be too difficult, no? Maybe if the renovation year is the same as the construction year, the data helper could give a warning and use the construction year as the reference value (instead of the renovation year)?

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro can you check if this is still the case, and if so implement the quick change you suggested?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA it is, and I can!

**Comment by martin-mosteiro** [comment]
Small update: the only difference appears to be `type_leak` in the envelope systems database. The thermal properties of a building built in 1992 and one renovated in 1992 appear to be the same.
