### ISSUE TITLE
Ventilation system properties to archetypes

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#387]
Building archetypes have to be equipped with ventilation system properties (similar to heating/cooling system properties). The current demand calculation uses some work around.

The list of properties includes:
- Mechanical ventilation: Yes/No
- Window ventilation: Yes/No
- Heat recovery: Yes/No/Type
- Night flushing/economizer: Yes/No
  -...

**Comment by daren-thomas** [comment]
- Heatrecovery: Type (with one option equivalent to "none" - this is how the other systems in the CEA work, generally, none is `T0`)

Also, note, that we can start from zero here, so instead of using `T0, T1, T2` as values, maybe settle on `HR0, HR1, HR2` so that these values remind the user of the type being used:
- MV: mechanical ventilation
- WV: window ventilation?
- HR: heat recovery
- NF: night flushing? (kinda weird)

Also, in code, you could use more descriptive constants instead of comparing to strings:

```
if heat_recovery_type == HR_NONE:
    # do stuff
elif heat_recovery_type == HR_AIRBOX:
   # do stuff
```

Also, this might be a place to add an object hierarchy for a base class `HeatRecoverySystem`.
