### ISSUE TITLE
Numerous issues with the embodied energy script

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#389]
I found a number of issues in the embodied energy and emissions calculation.

1. A minor issue: is there any reason to calculate _delta_year_ as 
        `envelope_df['delta_year'] = (envelope_df['envelope'] - year_to_calculate) * -1`
instead of the much simpler and easier to read:
        `envelope_df['delta_year'] = year_to_calculate - envelope_df['envelope']`?

2. A likely couple of typos: the contributions due to HVAC renovation include two mistakes. 
        `HVAC_df['delta_year'] = (`**`HVAC_df['basement']`**` - year_to_calculate) * -1` (uses the year of renovation of the basement instead of the year of renovation of the HVAC **`HVAC_df['HVAC']`**)
        `HVAC_df['confirm'] = HVAC_df.apply(lambda x: calc_if_existing(x['delta_year'], `**`gv.sl_materials`**`),axis=1)` (uses the service life of materials instead of the service life of services **`gv.sl_services`**)

On to the important stuff.

3. @JIMENOFONSECA what is `PFloor` exactly? It is only used for calculating the embodied energy/emissions of **windows (both building and renovation)**, **internal supporting walls** (**only building**, not renovation) and **external walls** (**only renovation**, not building). The fact that for the latter two this factor is only used for either building or renovation seems inconsistent.

Furthermore, for each of the cases described above, the embodied energy/emissions of the corresponding building component is multiplied by `(PFloor - 1)`. Since for every building in the area of study `PFloor` = 1, **the embodied energy and emissions of these components are not included in the calculation**. @JIMENOFONSECA is this meant to be that way?

4. Finally, for the construction as well as for the renovations, `built_df['confirm']`/`envelope_df['confirm']`/etc. are defined as 1 if the calculation year is within 60 years of the year of construction/renovation and 0 otherwise. However, this factor is only used for renovations. This means that:
- **for construction, `embodied energy = (embodied energy / 60)` regardless of the calculation year**
- **for renovation, `embodied energy = (embodied energy / 60)` if within 60 years of renovation
                            `embodied energy = 0` if the calculation year is more than 60 years after renovation.**
@JIMENOFONSECA Is there any reason for this difference? Is it a mistake, as it would seem?

**Comment by martin-mosteiro** [comment]
@amraladdin these are the issues I described in my email to you.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro my comments. would you assign it to yourself and go ahead with the changes?

A minor issue: is there any reason to calculate delta_year as
**agree**

A likely couple of typos: the contributions due to HVAC renovation include two mistakes.
**agree**

On to the important stuff.

@JIMENOFONSECA what is PFloor exactly?
**it is a flag to count with the % of the floors that have external walls. in most buildings it is 1, but in parking garages of 5 floors with a restaurant in the first floor the PFloor value is 0.2. We know about how confusing this variable is. If there is any other option we should go for it.**
 It is only used for calculating the embodied energy/emissions of windows (both building and renovation), internal supporting walls (only building, not renovation) and external walls (only renovation, not building). The fact that for the latter two this factor is only used for either building or renovation seems inconsistent. **not inconsistent. if a building without walls is renovated, it is assumed the walls will not be built unless there is a change in occupancy and PFloor value**

Furthermore, for each of the cases described above, the embodied energy/emissions of the corresponding building component is multiplied by (PFloor - 1).  for every building in the area of study PFloor = 1, the embodied energy and emissions of these components are not included in the calculation. @JIMENOFONSECA is this meant to be that way?**we might want to check this and do the changes accordingly, the -1 and the 'confirm' value was not part of my original implementation, perhaps @daren-thomas could you give us some insight?**

Finally, for the construction as well as for the renovations, built_df['confirm']/envelope_df['confirm']/etc. are defined as 1 if the calculation year is within 60 years of the year of construction/renovation and 0 otherwise. However, this factor is only used for renovations. This means that:
for construction, embodied energy = (embodied energy / 60) regardless of the calculation year
for renovation, embodied energy = (embodied energy / 60) if within 60 years of renovation
embodied energy = 0 if the calculation year is more than 60 years after renovation.
@JIMENOFONSECA Is there any reason for this difference? Is it a mistake, as it would seem?

**not a mistake, the calculation should account for the yearly emissions amortized in 60 years (accoridng to SIA). if a building was not renovated and the year calc is after 60 years there would not be any yearly emissions left**
**if year calc is beyond 60 years after renovation there would not be any yearly emissions left**

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Thanks for your answers! I forgot to assign the issue to myself, I've done it now.

> PFloor _it is a flag to count with the % of the floors that have external walls. in most buildings it is 1, but in parking garages of 5 floors with a restaurant in the first floor the PFloor value is 0.2. We know about how confusing this variable is. If there is any other option we should go for it._
Sounds okay to me, if anything maybe the name could be changed to something more intuitive.

> _not inconsistent. if a building without walls is renovated, it is assumed the walls will not be built unless there is a change in occupancy and PFloor value_
What I meant was inconsistent is that the **internal** walls are not included in the building calculation while the **external** walls are not included in the renovation calculation. For each of these components the contribution should be either both for construction and renovation or for neither. My guess is for PFloor = 0 the external walls, windows and internal non-supporting walls shouldn't be considered, but internal supporting walls should. What do you think?

> (PFloor - 1) _we might want to check this and do the changes accordingly, the -1 and the 'confirm' value was not part of my original implementation, perhaps @daren-thomas could you give us some insight?_
Now that I understand what PFloor means, I would say the external walls and windows should be multiplied by PFloor, **not** (PFloor-1). i.e., if PFloor = 0.2 (20% of building has external walls), the contribution from the windows is (A_window * E_window * 0.2). As currently written, if the building has walls in every floor (PFloor=1), no window or wall contribution is calculated, and if it doesn't (PFloor=0) then the window and wall contribution is included.

> _not a mistake, the calculation should account for the yearly emissions amortized in 60 years (accoridng to SIA). if a building was not renovated and the year calc is after 60 years there would not be any yearly emissions left_
> _if year calc is beyond 60 years after renovation there would not be any yearly emissions left_
I agree with some caveats:
1. Currently, the embodied emmissions for construction are consistenly 1/60 of the total amount, whereas for renovation they are 1/60 of the total amount iff the year of calculation is within 60 years of the renovation. So the total emissions for an arbitrary building built in 1920 and renovated in 1960 would look as follows
![example1](https://cloud.githubusercontent.com/assets/18548065/19885864/44c3fdb4-a021-11e6-8168-607cd30c3d9e.png)
2. It makes sense to amortize the embodied energy through 60 years if the building is less than 60 years old, but it just seems arbitrary to continue to use that value even after 60 years have passed. Wouldn't it be more reasonable to have the materials amortized through 60 years if the year to calculate is not within sixty years, and then delta_year=(year_to_calculate-year_built) after? Here is what the same building in the example above would look like:
![example2](https://cloud.githubusercontent.com/assets/18548065/19885913/827e47c2-a021-11e6-9a4d-3742d445f0b6.png)
@amraladdin This is what you were asking about yesterday.

**Comment by amraladdin** [comment]
@martin-mosteiro Yes, exactly! However, shouldn't the second graph have an always decreasing value? I mean since the beginning of the calculation? Cause in the case shown here, even without retrofitting, after 60 years the building embodied energy doesn't reach 0.

**Comment by JIMENOFONSECA** [comment]
One question, should not all go to 0 by 2020 in the example?

Best, Jimeno

On 1 Nov 2016, at 17:58, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Thanks for your answers! I forgot to assign the issue to myself, I've done it now.

PFloor it is a flag to count with the % of the floors that have external walls. in most buildings it is 1, but in parking garages of 5 floors with a restaurant in the first floor the PFloor value is 0.2. We know about how confusing this variable is. If there is any other option we should go for it.
Sounds okay to me, if anything maybe the name could be changed to something more intuitive.

not inconsistent. if a building without walls is renovated, it is assumed the walls will not be built unless there is a change in occupancy and PFloor value
What I meant was inconsistent is that the internal walls are not included in the building calculation while the external walls are not included in the renovation calculation. For each of these components the contribution should be either both for construction and renovation or for neither. My guess is for PFloor = 0 the external walls, windows and internal non-supporting walls shouldn't be considered, but internal supporting walls should. What do you think?

(PFloor - 1) we might want to check this and do the changes accordingly, the -1 and the 'confirm' value was not part of my original implementation, perhaps @daren-thomas<https://github.com/daren-thomas> could you give us some insight?
Now that I understand what PFloor means, I would say the external walls and windows should be multiplied by PFloor, not (PFloor-1). i.e., if PFloor = 0.2 (20% of building has external walls), the contribution from the windows is (A_window * E_window * 0.2). As currently written, if the building has walls in every floor (PFloor=1), no window or wall contribution is calculated, and if it doesn't (PFloor=0) then the window and wall contribution is included.

not a mistake, the calculation should account for the yearly emissions amortized in 60 years (accoridng to SIA). if a building was not renovated and the year calc is after 60 years there would not be any yearly emissions left
if year calc is beyond 60 years after renovation there would not be any yearly emissions left
I agree with some caveats:
1. Currently, the embodied emmissions for construction are consistenly 1/60 of the total amount, whereas for renovation they are 1/60 of the total amount iff the year of calculation is within 60 years of the renovation. So the total emissions for an arbitrary building built in 1920 and renovated in 1960 would look as follows
[example1]<https://cloud.githubusercontent.com/assets/18548065/19885864/44c3fdb4-a021-11e6-8168-607cd30c3d9e.png>
2. It makes sense to amortize the embodied energy through 60 years if the building is less than 60 years old, but it just seems arbitrary to continue to use that value even after 60 years have passed. Wouldn't it be more reasonable to have the materials amortized through 60 years if the year to calculate is not within sixty years, and then delta_year=(year_to_calculate-year_built) after? Here is what the same building in the example above would look like:
[example2]<https://cloud.githubusercontent.com/assets/18548065/19885913/827e47c2-a021-11e6-9a4d-3742d445f0b6.png>
@amraladdin<https://github.com/amraladdin> This is what you were asking about yesterday.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA not the way it is currently implemented in the CEA. In the CEA, the embodied energy/emissions due to construction are constantly 1/60 of the construction energy **forever** and the embodied energy/emissions are 1/60 of the renovation energy only when calculating within 60 years of renovation. That's why I'm saying that the calculation is not consistent.

**Comment by JIMENOFONSECA** [comment]
I see, so after 60 years of contruction there is no stop in the emissions in CEA. Let's fix that.

Best, Jimeno

On 1 Nov 2016, at 19:09, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> not the way it is currently implemented in the CEA. In the CEA, the embodied energy/emissions due to construction are constantly 1/60 of the construction energy forever and the embodied energy/emissions are 1/60 of the renovation energy only when calculating within 60 years of renovation. That's why I'm saying that the calculation is not consistent.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA That's what I meant in my first message. Guess that was just a misunderstanding. I've now fixed all the above issues and created a pull request.
