### ISSUE TITLE
Fix optimization use of InputLocator

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#423]
The optimization code uses a different approach to the InputLocator than the rest of the code: It assigns local variables to the InputLocator and uses those instead of the `get_*` methods employed by the rest of the CEA.

Refactor those usages to the standard model and at the same time make sure folders referenced exist.

**Comment by daren-thomas** [comment]
Started working on branch `423-fix-optimization-use-of-inputlocator`. Since this leads to refactoring, I first need to be able to verify I am not changing results. @JIMENOFONSECA: How do we test the current functionality of the optimization?

**Comment by JIMENOFONSECA** [comment]
Uhoh... My PR of documenting optimization has this in place and it is 100% functional. We might want to merge that branch first and then see if the input locator issue persists

Best, Jimeno

On 28 Nov 2016, at 20:23, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Started working on branch 423-fix-optimization-use-of-inputlocator. Since this leads to refactoring, I first need to be able to verify I am not changing results. @JIMENOFONSECA<https://github.com/JIMENOFONSECA>: How do we test the current functionality of the optimization?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, so, I just branched from master again, after merging your PR. It is not 100% functional. 
- I ran the `optimization_main` script but got an error "no module `slave_main`" - the module was named `Slave_main.py`, so I renamed that
- next, I get an error `IOError: File c:\reference-case-zug\baseline\outputs\data\potentials\solar/Pv.csv does not exist`

Could you check on the master branch if the optimization code is still working for you?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas worse than that, the demand.py doe snot work anymore.... @gabriel-happle does the demand_main.py iwork for you?

![image](https://cloud.githubusercontent.com/assets/8973186/20738119/f91ca136-b6eb-11e6-80b2-ba7899675fc9.png)

**Comment by gabriel-happle** [comment]
This warning is coded by me. It is from the HVAC script enthalpy calculation. meaning that some air temperatures are higher than 60°C... I just tested the demand for my pull request #425 - no issues

**Comment by gabriel-happle** [comment]
All these things will not happen anymore with my major update (I hope)

**Comment by daren-thomas** [comment]
can confirm: current master has no warnings. everything is a-ok. there was one warning, apparently `df.sort` is deprecated, moved to `df.sort_values`.
