### ISSUE TITLE
Unnecessary function in embodied energy script

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#484]
The embodied energy script includes the following function:
'''
def calc_comparison(array_min, array_max):
    if array_max == 'DEPO':
        if array_min != 'DEPO':
            array_max = array_min
    return array_max
'''
What this does is check which building use is most common and least common in a building and, if the most common use is **'DEPO'**, change the value of the most common use to the least common use. However, there is no building occupancy type **'DEPO'** in the CEA right now, so this function won't actually do anything.

@JIMENOFONSECA: is there any reason to keep this? If so, which occupancy type should be used instead of **'DEPO'**?

**Comment by JIMENOFONSECA** [comment]
Yes, it happens when you have a restaurant in the ground floor and 5 stories of parking or deposit. In zug we had this case

Best, Jimeno

On 9 Feb 2017, at 22:29, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


The embodied energy script includes the following function:
'''
def calc_comparison(array_min, array_max):
if array_max == 'DEPO':
if array_min != 'DEPO':
array_max = array_min
return array_max
'''
What this does is check which building use is most common and least common in a building and, if the most common use is 'DEPO', change the value of the most common use to the least common use. However, there is no building occupancy type 'DEPO' in the CEA right now, so this function won't actually do anything.

@JIMENOFONSECA<https://github.com/JIMENOFONSECA>: is there any reason to keep this? If so, which occupancy type should be used instead of 'DEPO'?

**Comment by martin-mosteiro** [comment]
The ocuppancy type the script looks for should be renamed from 'DEPO' to 'PARKING' since we don't have any occupancy type 'DEPO'. I'll fix it.

**Comment by JIMENOFONSECA** [comment]
A cool :-)

Best, Jimeno

On 10 Feb 2017, at 15:06, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:

The ocuppancy type the script looks for should be renamed from 'DEPO' to 'PARKING' since we don't have any occupancy type 'DEPO'. I'll fix it.

**Comment by martin-mosteiro** [comment]
Fixed by PR #491
