### ISSUE TITLE
User manual updates

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#489]
I Just created this issue to keep track of everyone's suggestions to improve the user manual as requested by @amraladdin 
@daren-thomas @gabriel-happle @BhargavaKrishnaSreepathi @shanshanhsieh @shizhongming please check the guide and add your comments and  recommendations in here.

**Comment by BhargavaKrishnaSreepathi** [comment]
Hey amr: here are my comments about the user manual
1. In the 'Get Started' page, we are not providing any details about DBF reader, so should it be mentioned? It is in the first paragraph of the page
2. At the bottom of the same page, there is a section about 'Main Steps'. I did not understand the necessity of it on this page. Is there any reason?
3. Sorry for being so picky, in the page 'creating multiple scenarios', under the section of 'modifying building properties', in the third line, it should be 'changed' instead of 'changes'
4. 'Visualise' is more of british english, i think it should be 'Visualizing'. This happens multiple times on the page 'Visualising Results'

**Comment by JIMENOFONSECA** [comment]
@amraladdin It is a great starting point and i see it is well structured and easy to read. I mention some points that could be covered and add the questions that each topic should answer to the reader.

1. Guide to modify geometry: how do i create a new scenario and modify, the height, location and 2D vertices of buildings directly in ArcGIS?. How do I add a some new buildings either using ArcGIS or Autocad? 
2. while presenting the process of running a quick simulation it would be great to know: Where and what are the rdata being created?. 
3. Benchmarking graphs of the 2000-watt society: This part is just missing. @martin-mosteiro worked in it.

Other than that i see it works perfectly with teh current version of CEA.

**Comment by amraladdin** [comment]
Update from @JIMENOFONSECA 
-----------------------------------
PR 531 introduces a new structure of databases:

1. basically the thermal_properties.shp is erased. most of the values contained in this shapefile now will exist in the architecture.shp for the sake of simplicity. @martin-mosteiro please consider this for the HQ case study. If you upload it to the private repository we will make this change for you inmediately.

2. in connection to this, the database envelope_systems.xls will now handle the thermal properties of the Archetypes_properties.xls/THERMAL. With this update, the type of windows, walls and roof are strongly related to a certain U value / Gvalue and etc. This will allow to create new construction material in CEA in agreement with different building certification approaches.

2. It makes all the files in the building-properties folder a type .dbf instead of .shp.  If the case studies have .shp this is not a problem, so no need to change previous case studies. .dbf make better the managment of data and avoids changes in geometry of one file to be reflected in any other shapefile. @amraladdin means that everytime you wanna map a value from the building-properties folder it is necessary to do a join to the zone.shp file to visualize it. Please take into account this in the documentatio

**Comment by amraladdin** [comment]
@BhargavaKrishnaSreepathi Regarding your first comment... The DBF reader, could you provide the information necessary there? I'm not familiar with the DBF reader.

Regarding point no. 2... you're right, I should add this part to the quick simulation introduction. It basically shows the main steps users need to go through in order to create a successful simulation.

Points 3 and 4 are done... Please feel free to be as picky as possible. The aim here is to provide a professional manual for the CEA users, so no worries... Shoot :)

**Comment by BhargavaKrishnaSreepathi** [comment]
@amraladdin meant to tag you @JIMENOFONSECA i guess :)

**Comment by amraladdin** [comment]
:D maybe I meant to tag both of you Bharga, cause I was referring to the first point in your comment :) but you're right, Jimeno also mentioned it in his 3rd point in the update I added yesterday :)

So, if any of you guys can add this to the manual, it would be great! Otherwise, I would need more time to learn more about it and implement it!

**Comment by amraladdin** [comment]
SUMMARY FOR TOMORROW
-------------------------------
@BhargavaKrishnaSreepathi 's points 2, 3 and 4 are fixed. However, for point no.1, I will need someone to create the DBF reader part, this also applies to Jimeno's update comment on the building properties.

@JIMENOFONSECA 's point 3 is finished, @martin-mosteiro will help me with point no. 1 and I will get on point no. 2 after the meeting.

**Comment by amraladdin** [comment]
@JIMENOFONSECA @BhargavaKrishnaSreepathi @daren-thomas @martin-mosteiro @gabriel-happle @shanshanhsieh @shizhongming Which of you will help me with the DBF reader steps in the Users' Manual?
