### ISSUE TITLE
Code the program that can run the CEA and send back the result in Rhino/Grasshopper

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CEAforArcGIS#566]
![workflow status quo ubg](https://cloud.githubusercontent.com/assets/16640327/24385073/87ea9d40-139a-11e7-8518-34f6cd5ae9fa.png)

Hi Darren, this issue is as we discussed when you were in Singapore. I also attached a diagram to explain the workflow. Let me know if you have any questions~

**Comment by amraladdin** [comment]
Dear all,

Would it be possible to organize a meeting with you ( @daren-thomas , @shizhongming , @JIMENOFONSECA ) in order to discuss the work done with the Grasshopper CEA Plugin?

To brief Zhongming, I presented a suggestion in the last Chair retreat (1st of June) here in Zurich, which discussed the option of creating our own components on GH that focus on systems. The aim is to create very lean and simple components to work with, which also allows the addition of levels of complexity.

How about we meet after our next bi-weekly meeting? Thursday the 15th of June (30 minutes)?

Looking forward to your feedback.

**Comment by daren-thomas** [comment]
OK. So. The branch `566-code-the-program-to-call-cea-from-gh` has a grasshopper user object (`urban_design/CEA demand.ghuser`) that does this:

![image](https://user-images.githubusercontent.com/2969564/27123069-ffe48a38-50ec-11e7-8df6-a26e8c2382a9.png)

**Comment by amraladdin** [comment]
Super!
Has anyone had the time to look at my previous comment? @JIMENOFONSECA @shizhongming @daren-thomas

**Comment by shizhongming** [comment]
@amraladdin we did discuss about having the CEA inside grasshopper as a component. But if the "calling" component Darren is making here works, I think it would work the same. This is very similar to using energyplus with honeybee in grasshopper. 
Good idea, lets meet tomorrow~

**Comment by daren-thomas** [comment]
so here is an updated version, zhonming:

![image](https://user-images.githubusercontent.com/2969564/27124752-4f44c5ca-50f2-11e7-985c-4e62a8b54be0.png)

**Comment by daren-thomas** [comment]
i think this issue is fixed with PR #680

**Comment by shizhongming** [comment]
@daren-thomas Great! I think can leave it like this for now. We can test it the loop when I finish my issue. ThX~

**Comment by daren-thomas** [comment]
so... can we close the issue? did you test to see if it runs on your machine?

**Comment by shizhongming** [comment]
Trying to test the issue now

**Comment by shizhongming** [comment]
@daren-thomas just tested, it is working well! Really cool! Thanks!

**Comment by daren-thomas** [comment]
@shizhongming can we close the issue?
