### ISSUE TITLE
'Age', 'Occupancy' and 'Supply Systems' description missing from GitBook Manual

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#617]
Some of the Building Properties, e.g. Age, Occupancy and Supply Systems inputs are missing from the GitBook inputs description. @martin-mosteiro and I tried to find them, but they're not there.
@JIMENOFONSECA who was working on this part? Perhaps they have the data still, but missed to add them to the manual.

**Comment by JIMENOFONSECA** [comment]
Gitbook is not anymore our manual as discussed in January 2017. If something is missing is  because we took too long to pass the info to the cea website. So please ask directly about the variables that are not defined.


On 25 Apr 2017, at 17:21, Amr Elesawy <notifications@github.com<mailto:notifications@github.com>> wrote:


Some of the Building Properties, e.g. Age, Occupancy and Supply Systems inputs are missing from the GitBook inputs description. @martin-mosteiro<https://github.com/martin-mosteiro> and I tried to find them, but they're not there.
@JIMENOFONSECA<https://github.com/JIMENOFONSECA> who was working on this part? Perhaps they have the data still, but missed to add them to the manual.

**Comment by amraladdin** [comment]
Still, my question was, who was working on the building properties part?
In the title, the Age, Occupancy and Supply systems inputs description is missing.

**Comment by JIMENOFONSECA** [comment]
I think i was working on it, you mean you need the description of the Variables of the input databases of age, occupancy etc? Check the how to guide in the FAQ section for this.

Our Gitbook is kind of obsolete and should  not be updated anymore.

On 25 Apr 2017, at 23:54, Amr Elesawy <notifications@github.com<mailto:notifications@github.com>> wrote:


Still, my question was, who was working on the building properties part?
In the title, the Age, Occupancy and Supply systems inputs description is missing.

**Comment by JIMENOFONSECA** [comment]
@amraladdin does this solve your question?

**Comment by amraladdin** [comment]
Yes, this is perfect! Thanks!
