### ISSUE TITLE
FAQ: How to edit input databases of CEA?

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#644]
I Made the slides, @amraladdin can you check if this is the case, if not complement it and close the issue? thanks!

**Comment by amraladdin** [comment]
Thanks a lot @JIMENOFONSECA I'll check them and report accordingly!

**Comment by JIMENOFONSECA** [comment]
@amraladdin any update? :-)

**Comment by amraladdin** [comment]
@JIMENOFONSECA Working on it. Will send an update end of today :)

**Comment by amraladdin** [comment]
Done. So, I made some changes in the text of the first few slides. I've also changed half of the images (Somehow, they had a very bad quality, did you change the settings of the images?).
So, if you have time to look at it, that's great, then we can close this issue. Otherwise, if you don't have time, I'll revise the presentations on Wednesday.
