### ISSUE TITLE
Zurich case is missing terrain

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#676]
The Zurich main case includes new buildings outside of the current Digital Elevation Model. It is necessary to fix this in order to pass #662. 

The steps to do this are:
1. download a new DEM from Geovite at ETHz  or Openmaps.
2. re-sample the DEM to a grid higher than 50m. the bigger the grid is, the less computation time the radiation calculation will take.

**Comment by martin-mosteiro** [comment]
I uploaded the new DEM for the Hoschulquartier case study.
As discussed with Jimeno, I also modified the Baseline scenario to reduce the total number of buildings in the shapefile by about two thirds (since most of them had no to negligible effect on the radiation calculation).
I will now update the Masterplan scenario to include the above modification plus some other updates I have worked on the past month or so.
Once the Masterplan scenario is also updated I will create a pull request.

**Comment by martin-mosteiro** [comment]
This issue is solved by [PR #15 in the reference-case repository](https://github.com/architecture-building-systems/cea-reference-case/pull/15)

**Comment by martin-mosteiro** [comment]
As mentioned on #368 two buildings were still missing from the Hochschulquartier reference case. Plattenstrasse 22/24 was added based on [the building plans](oerebdocs.zh.ch/getDoc?docid=4023). The Hirschengrabenbau was also added, though since no plans could be found it was based on [the ground floor area](http://www.are.zh.ch/dam/baudirektion/are/raumplanung/kantonalerrichtplan/vorlagen/oeba_4349/antrag_regierungsrat/Phase_2_masterplan_minimal.pdf.spooler.download.1400169900471.pdf/Phase_2_masterplan_minimal.pdf), the height was assumed to be the same as the current maximum height and the number of floors was assumed based on the current useable floor area and the future useable floor area (HNF).
